//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTestDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Security;

    public partial class tblLogin
    {

        public int eLoginId { get; set; }
        [Required(ErrorMessage = "This field is Required")]        
        public string eFirstName { get; set; }
        [Required(ErrorMessage = "This field is Required")]        
        public string eLastName { get; set; }
        [Required(ErrorMessage = "This field is Required")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string eEmail { get; set; }
        public string eUsername { get; set; }

        [Required(ErrorMessage = "This field is Required")]
        [MembershipPassword(
        MinRequiredNonAlphanumericCharacters = 1,
        MinNonAlphanumericCharactersError = "Your password needs to contain at least one symbol (!, @, #, etc).",
        ErrorMessage = "Your password must be 6 characters long and contain at least one symbol (!, @, #, etc).",
        MinRequiredPasswordLength = 6)]
        public string ePassword { get; set; }
        [Required(ErrorMessage = "This field is Required")]
        
        [Compare("ePassword", ErrorMessage = "Passwords don't match")]
        public string eConfirmPassword { get; set; }
        //[Required(ErrorMessage = "This field is Required")]
        public string Role { get; set; }
        //[Required(ErrorMessage ="Enter OTP")]
        public string OTP { get; set; }
    }
}
